# Generated by Django 5.1.2 on 2026-02-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='eyebrow',
            field=models.CharField(blank=True, help_text="Small text above title (e.g., 'Dubai's Premier...')", max_length=200),
        ),
        migrations.AddField(
            model_name='hero',
            name='secondary_cta_link',
            field=models.CharField(blank=True, help_text='Secondary CTA button link', max_length=255),
        ),
        migrations.AddField(
            model_name='hero',
            name='secondary_cta_text',
            field=models.CharField(blank=True, help_text='Secondary CTA button text', max_length=100),
        ),
        migrations.AddField(
            model_name='hero',
            name='stats_data',
            field=models.CharField(blank=True, help_text="Stats in format: '3+|Years in Dubai,340+|Projects Completed,98%|Client Satisfaction'", max_length=500),
        ),
        migrations.AlterField(
            model_name='hero',
            name='cta_link',
            field=models.CharField(blank=True, help_text='Primary CTA button link', max_length=255),
        ),
        migrations.AlterField(
            model_name='hero',
            name='cta_text',
            field=models.CharField(blank=True, help_text='Primary CTA button text', max_length=100),
        ),
    ]
