# Generated by Django 5.1.2 on 2026-02-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_hero_eyebrow_hero_secondary_cta_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='cta_link',
            field=models.CharField(blank=True, help_text='Hero CTA button link', max_length=255),
        ),
        migrations.AddField(
            model_name='service',
            name='cta_text',
            field=models.CharField(blank=True, help_text='Hero CTA button text', max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='faq_data',
            field=models.TextField(blank=True, help_text="FAQ in format: 'How long does it take?|Most residential...'"),
        ),
        migrations.AddField(
            model_name='service',
            name='hero_meta_guarantee',
            field=models.CharField(blank=True, help_text="Guarantee stat (e.g., '2 Yrs')", max_length=50),
        ),
        migrations.AddField(
            model_name='service',
            name='hero_meta_projects',
            field=models.CharField(blank=True, help_text="Projects stat (e.g., '140+')", max_length=50),
        ),
        migrations.AddField(
            model_name='service',
            name='hero_meta_satisfaction',
            field=models.CharField(blank=True, help_text="Satisfaction stat (e.g., '4.9 ★')", max_length=50),
        ),
        migrations.AddField(
            model_name='service',
            name='hero_tag',
            field=models.CharField(blank=True, help_text="Tag shown in hero (e.g., 'Outdoor Landscaping')", max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, help_text="Font Awesome icon class (e.g., 'fa-tree')", max_length=50),
        ),
        migrations.AddField(
            model_name='service',
            name='overview_content',
            field=models.TextField(blank=True, help_text='Overview paragraphs (separate with double newline)'),
        ),
        migrations.AddField(
            model_name='service',
            name='process_steps_data',
            field=models.TextField(blank=True, help_text="Process steps in format: 'fa-search|Discovery & Site Analysis|Description...'"),
        ),
        migrations.AddField(
            model_name='service',
            name='related_services',
            field=models.CharField(blank=True, help_text='Comma-separated service slugs for related services', max_length=500),
        ),
        migrations.AddField(
            model_name='service',
            name='showcase_projects_data',
            field=models.TextField(blank=True, help_text="Showcase projects in format: 'Dubai Hills Estate|The Palm Residence Garden|large,...'"),
        ),
        migrations.AddField(
            model_name='service',
            name='specs_data',
            field=models.TextField(blank=True, help_text="Specs in format: 'Minimum Plot|200 sqm...,Design Style|Tropical...'"),
        ),
        migrations.AddField(
            model_name='service',
            name='stats_strip_data',
            field=models.TextField(blank=True, help_text="Stats in format: '140+|Villas Transformed|Across Dubai...,3–8|Weeks to Completion|Depending on...'"),
        ),
        migrations.AddField(
            model_name='service',
            name='testimonial_author',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='testimonial_role',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='testimonial_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='timeline_data',
            field=models.TextField(blank=True, help_text="Timeline in format: 'Week 1|Task description,Week 2|Task description'"),
        ),
        migrations.AddField(
            model_name='service',
            name='whats_included',
            field=models.TextField(blank=True, help_text="What's included list items (one per line)"),
        ),
    ]
