# Generated by Django 5.1.2 on 2026-02-22 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_processstep'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('location', models.CharField(help_text="Location (e.g., 'Dubai Hills Estate')", max_length=200)),
                ('category', models.CharField(help_text="Category/tags (e.g., 'Villa Landscaping + Pool')", max_length=200)),
                ('hero_image_url', models.URLField(blank=True, help_text='Cloudinary URL for hero/featured image')),
                ('short_description', models.TextField(blank=True, help_text='Brief description for cards')),
                ('full_description', models.TextField(blank=True, help_text='Full project description')),
                ('specs_data', models.TextField(blank=True, help_text="Project specs in format: 'Area|500 sqm,Completion|2024,Style|Tropical Modern'")),
                ('gallery_images', models.TextField(blank=True, help_text='Comma-separated Cloudinary URLs for gallery')),
                ('featured', models.BooleanField(default=False, help_text='Show on homepage portfolio section')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='myApp.service')),
            ],
            options={
                'ordering': ['-featured', 'order', '-created_at'],
            },
        ),
    ]
