# Generated by Django 5.1.2 on 2026-02-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntroSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_image_url', models.URLField(blank=True, help_text='Cloudinary URL for intro section image (replaces SVG)')),
                ('use_svg_fallback', models.BooleanField(default=True, help_text='Use SVG illustration if no image URL is provided')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Intro Settings',
                'verbose_name_plural': 'Intro Settings',
            },
        ),
    ]
